### PR TITLE
fix: add check for disabled session storage

### LINKED ISSUE #57: Method to work around disabled cookies in browser
Hi! We are trying to make LSM work with disabled cookies in the browser. This disables localStorage and sessionStorage in most browsers. This makes even trying to access window.sessionStorage return an access denied exception.

Our solution is to call setStorageType and save to app memory if sessionStorage is disabled.
```javascript
// Run this only if sessionStorage is disabled or does not exist
const state = {}  
setStorageType({
  setItem: (key, value) => {
    state[key] = value
  },
  getItem: item => state[item],
})
```

Now normally this should work, but there appears to be a line in the LSM source that depends on sessionStorage being enabled, making our app crash.

```typescript
let storageType: Storage = isClient
  ? window.sessionStorage
  : {
      getItem: payload => payload,
      setItem: (payload: string) => payload,
      clear: () => {},
      length: 0,
      key: (payload: number) => payload.toString(),
      removeItem: () => {},
    };
```

In the code above, window.sessionStorage is called, but this crashes our app if it is not available. Of course, we could (try to) use require with a try-catch instead of imports, but we'd rather avoid that.

Would you guys be open to returning null/undefined/otherwise ignore the error if window.sessionStorage is not allowed?

Thanks!

### PR DESCRIPTION
**Pull request by MattL75**
Adds a check for window.sessionStorage. If it does not exist or if accessing it creates an exception (like with disabled cookies) it will return false. Otherwise, it will return true.

Feel free to modify if you need @bluebill1049  👍 

closes #57

### CODE REVIEW

File: src/utils/isSessionStorageAllowed.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export default (): boolean => {
+    try {
+      return window.sessionStorage !== null
```
Comment (bluebill1049) [inline src/utils/isSessionStorageAllowed.ts:3]: `!!window.sessionStorage` enough?

**Comment by bluebill1049** [comment]
Thanks a lot for the PR, looks good 👍 just a minor one.

File: src/utils/isSessionStorageAllowed.ts (hunk 1 above)
Comment (MattL75) [reply src/utils/isSessionStorageAllowed.ts]: yup

**Comment by MattL75** [comment]
@bluebill1049 Fixed PR :)

**Comment by bluebill1049** [comment]
thanks! 👍

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
will release a beta version, let me know if this is working as expected.

**Comment by bluebill1049** [comment]
`3.2.0-beta.1`

**Comment by MattL75** [comment]
Works great! Thanks
