### PR TITLE
fix issue with reading asyc store

### LINKED ISSUE #48: AsyncStorage doesn't work with react-native
I don't see how this should currently work, since AsyncStorage is async.... ?

At least I don't know how to make it work in my App. It doesn't restore / or save the data.

Any hints would be helpful. Thank you ❤️ 

```jsx
import React from 'react';
import AsyncStorage from '@react-native-community/async-storage';
import {
  StateMachineProvider,
  createStore,
  setStorageType,
} from 'little-state-machine';

import App from './App';

setStorageType(AsyncStorage);

const data: LittleState = {
  xFormData: {},
};

createStore(data);

const AppContainer = () => (
    <StateMachineProvider>
        <App />
    </StateMachineProvider>
);

export default AppContainer;
```

### PR DESCRIPTION
**Pull request by bluebill1049**
close #48

### CODE REVIEW

File: src/logic/getBrowserStoreData.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
-export default (storageType: Storage, storeName: string) => {
-  const sessionStorageData = storageType.getItem(storeName);
+export default async (storageType: Storage, storeName: string) => {
+  const sessionStorageData = await storageType.getItem(storeName);
   try {
```
Comment (happyfloat) [inline src/logic/getBrowserStoreData.ts:3]: Maybe we should move the await also in the try catch block.

Comment (bluebill1049) [reply src/logic/getBrowserStoreData.ts:3]: sounds good to me.
